### ISSUE TITLE
Any plans to make a zepto-friendly version of jquery_ujs?

### ISSUE THREAD

**Issue by cannikin** [stefanvermaas/zepto-for-rails#3]
I'd LOVE to use zepto going forward but Rails's jquery_ujs isn't compatible. :( There's no `ajaxPrefilter` method in zepto and apparently Rails relies on it for CSRF stuff. Any idea if it'd be possible to provide the same functionality in a new zepto_ujs that could be distributed here?

**Comment by jeroenvisser101** [comment]
@cannikin – You could use [rails-behaviors](https://github.com/josh/rails-behaviors) for that

**Comment by stefanvermaas** [comment]
Hi @cannikin, sorry for the late response. I don't use Zepto in ongoing rails projects anymore, but if you still love to see this functionality, I encourage you to open a PR.
