### ISSUE TITLE
Release new version of zepto 1.2.0

### ISSUE THREAD

**Issue by Eric-Guo** [stefanvermaas/zepto-for-rails#4]
Appreciate if you have time to [upgrade to 1.2.0](https://github.com/madrobby/zepto/releases/tag/v1.2.0)

**Comment by stefanvermaas** [comment]
Hi @Eric-Guo, thanks for the heads up!

I don't use zepto anymore in a ongoing project, so I can't verify everything keeps working. Do you mind trying out the new zepto version? I've created a new branch: https://github.com/stefanvermaas/zepto-for-rails/tree/zepto-1.2.0

Thanks for your contribution!

**Comment by Eric-Guo** [comment]
Yes, no problem, Thank you!
I will trying out the new zepto version branch in my project and feedback after couple days if not problem found. (or give PR if required)

**Comment by stefanvermaas** [comment]
Awesome! I've created a [PR](https://github.com/stefanvermaas/zepto-for-rails/pull/5), so let me know if you run into any problems. Thanks!

**Comment by stefanvermaas** [comment]
This is merge into the master. New gem version: 0.3.0 (already published).
